# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ij7vQmfJ3ogXJ8asnS_ohdMBTHXV6UwJ

# **Predicting Home Prices using Linear Regression Model   **
"""

# Importing important libraries and modules

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

# Accesing and reading data
df = pd.read_csv("sample_data.csv")
df

# Commented out IPython magic to ensure Python compatibility.
# Pl0ting and visualizing the data 
# %matplotlib inline

plt.xlabel("area (Sqr ft)", fontsize = 15)
plt.ylabel('price (US$)', fontsize = 15)
plt.scatter(df.area, df.price, color = "red", marker = '+')

# Applying Linear Regression to train the model
input_data = df.area
output_data = df.price

#input_data.reshape(-1,1)
reg = linear_model.LinearRegression()
reg.fit(df[['area']], output_data)

# checking the performance of the model
reg.predict([[4450]])

# checking the co-efficient and intercept
m = reg.coef_

b = reg.intercept_

# verifying the price manually 
# y = mx + b
y = m * (4450) + b
print(y)

# Commented out IPython magic to ensure Python compatibility.
# Pl0ting and visualizing the data 
# %matplotlib inline

plt.xlabel("area (Sqr ft)", fontsize = 15)
plt.ylabel('price (US$)', fontsize = 15)
plt.scatter(df.area, df.price, color = "red", marker = '+')
plt.plot(df.area, reg.predict(df[['area']]), color = 'blue')

# To predict the prices of the large data
test_d = pd.read_csv("test_data.csv")
test_d

output_res = reg.predict(test_d)

#updated dataframe will be
test_d['price'] = output_res
test_d

# NOw exporting the dataframe back to csv to have the prices of the houses opredicted as

test_d.to_csv("Predicted.csv", index = False)